import {
	MdDashboard,
	MdInfoOutline,
	MdOutlineRealEstateAgent,
	MdOutlinePayments,
	MdOutlinePointOfSale,
	MdCampaign,
	MdLightbulb,
	MdDescription,
	MdTimeline,
	MdPeople,
	MdAssessment,
	MdShowChart,
	MdCompareArrows,
	MdAttachMoney,
	MdGavel,
	MdSearch,
	MdPersonSearch,
	MdStar,
	MdFolder,
	MdVerified,
	MdPolicy,
	MdPayments,
	MdInsights,
	MdBalance,
	MdCalculate,
	MdHistory,
	MdLeaderboard,
	MdStackedBarChart,
	MdOutlineAdminPanelSettings,
	MdGroup,
	MdOutlineTrendingUp,
	MdCo2,
	MdOutlineDocumentScanner,
	MdOutlineInsertPhoto,
	MdOutlineTerrain,
	MdOutlinePhotoSizeSelectActual,
	MdSettings,
	MdViewModule,
	MdOutlineWork,
} from 'react-icons/md';

import { FaUsers, FaRegBuilding, FaPlus } from 'react-icons/fa';
import { IconType } from 'react-icons/lib';
import { IoWater, IoBulb, IoDocumentTextOutline } from 'react-icons/io5';
import { FaChartGantt } from 'react-icons/fa6';
import { GrGallery } from 'react-icons/gr';

const iconMap: { [key: string]: IconType } = {
	MdDashboard,
	MdInfoOutline,
	MdOutlineRealEstateAgent,
	MdOutlinePayments,
	MdOutlinePointOfSale,
	MdCampaign,
	MdLightbulb,
	MdDescription,
	MdTimeline,
	MdPeople,
	MdAssessment,
	MdShowChart,
	MdCompareArrows,
	MdAttachMoney,
	MdGavel,
	MdSearch,
	MdPersonSearch,
	MdStar,
	MdFolder,
	MdVerified,
	MdPolicy,
	MdPayments,
	MdInsights,
	MdBalance,
	MdCalculate,
	MdHistory,
	MdLeaderboard,
	MdStackedBarChart,
	MdOutlineAdminPanelSettings,
	MdGroup,
	MdCo2,
	MdOutlineDocumentScanner,
	MdOutlineTrendingUp,
	MdOutlineInsertPhoto,
	MdOutlineTerrain,
	MdOutlinePhotoSizeSelectActual,
	MdSettings,
	MdViewModule,
	MdOutlineWork,

	FaUsers,
	FaRegBuilding,
	FaPlus,

	IoWater,
	IoBulb,
	IoDocumentTextOutline,

	FaChartGantt,

	GrGallery,
};

export default function getIconByName(iconName: string): IconType | undefined {
	return iconMap[iconName];
}
